name: remix_workspace
environment:
  sdk: ">=3.10.0 <4.0.0"
dependencies:
  mix: ^2.0.0-rc.0
  naked_ui: ^0.2.0-beta.7
  meta: ^1.16.0
dev_dependencies:
  melos: ^7.1.1
  dart_code_metrics_presets: ^2.26.1
  analyzer: ^8.0.0
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1

workspace:
  - packages/demo
  - packages/example
  - packages/playground
  - packages/remix

melos:
  packages:
    - packages/*

  command:
    bootstrap:
      environment:
        sdk: ">=3.10.0 <4.0.0"
        flutter: ">=3.38.1"

  scripts:
    test:flutter:
      run: melos exec -- flutter test
      description: Run flutter test
      packageFilters:
        dirExists: test

    ci:
      run: melos run test:flutter
      description: Run flutter and dart tests
      packageFilters:
        dirExists: test
