name: remix
description: Remix is a modern, expressive design system built on top of Naked and Mix.
repository: https://github.com/btwld/remix
documentation: https://docs.page/btwld/remix
issue_tracker: https://github.com/btwld/remix/issues
license: BSD-3-Clause
resolution: workspace
publish_to: none

version: 0.1.0-beta.3

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  mix: ^2.0.0-rc.1
  mix_annotations: ^2.0.0-rc.1
  naked_ui: ^0.2.0-beta.7
  meta: ^1.16.0
  prism: ^2.0.0
  prism_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.10.1
  mix_generator: ^2.0.0-rc.1

flutter:
  uses-material-design: true
