name: remix
description: Remix is a modern, expressive design system built on top of Naked and Mix.
repository: https://github.com/btwld/remix
documentation: https://docs.page/btwld/remix
issue_tracker: https://github.com/btwld/remix/issues
license: BSD-3-Clause
resolution: workspace

version: 0.1.0-beta.1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"


dependencies:
  flutter:
    sdk: flutter
  mix: ^2.0.0-dev.5
  naked_ui: ^0.2.0-beta.7
  prism: ^2.0.0
  prism_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
