name: demo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependency_overrides:
  accessibility_tools: ^2.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^3.9.0
  widgetbook: ^3.20.2
  remix: 
    path: ../remix

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true
