name: demo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.8.0
  remix: 
    path: ../remix

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.8.0

flutter:
  uses-material-design: true
